variables:
# Generic variables
  - name: azure_subscription
    value: "bf9e1a1a-dfec-417c-afa4-fd2fe4aaf814"
  - name: app_acronym
    value: "leostart"
  - name: env
    value: "dev"
  - name: location
    value: "eastus2"
# DevOps 
  - name: devops_rg
    value: "helleng-devops"
  - name: devops_storage_account
    value: "sthellengdevops"


# Resource naming convention
  - name: resource_group_name
    value: "$(app_acronym)-$(env)-rg"
  - name: keyvault_name
    value: $(app_acronym)$(env)kv
  - name: storage_account_name
    value: "$(app_acronym)$(env)stg"
  - name: adf_name
    value: "$(app_acronym)$(env)-adf"
  - name: container_name
    value: "sourcedata"
  - name: vnet_name
    value: "$(app_acronym)$(env)-vnet"
  - name: nsg_name
    value: "$(app_acronym)$(env)-nsg"
  - name: pe_subnet
    value: "$(app_acronym)$(env)-pe-snet"
  - name: app_subnet
    value: "$(app_acronym)$(env)-app-snet"
  - name: mssql_server_name
    value: "$(app_acronym)$(env)-mssql-sl2"
  - name: mssql_db_name
    value: "$(app_acronym)$(env)db"


  - name: mysql_server_name
    value: "$(app_acronym)$(env)-msql-flex"
  - name: mysql_db_name
    value: "$(app_acronym)$(env)db"
  - name: mysql_dns_name
    value: "$(app_acronym).mysql.database.azure.com"
  - name: mysql_subnet
    value: "$(app_acronym)$(env)-mysql-snet"


# KeyVault access
  - name: access_to_keyvault_1
    value: "a61ca04a-54ea-461f-b6ac-70c744f3d414" # Glib Account
  - name: access_to_keyvault_2
    value: "3ea4fe38-9f02-4e58-82cf-4679dce84cdc" # SP account
# Storage ADLS
  - name: my_ip
    value: "69.112.12.53"

# Git details for ADF
  - name: account_name
    value: "GlibMartynenko"
  - name: branch_name
    value: "main"
  - name: source_control
    value: "github.com"
  - name: repository_name
    value: "fiver_leo_sport_adf"
